const UserActionType = {
  SET_CURRENT_USER: "SET_CURRENT_USER",
  IS_USER_ADMIN: "IS_USER_ADMIN",
  GOOGLE_SIGN_IN_START: 'GOOGLE_SIGN_IN_START',
  GOOGLE_SIGN_IN_SUCCESS: 'GOOGLE_SIGN_IN_SUCCESS',
  GOOGLE_SIGN_IN_FAILURE: 'GOOGLE_SIGN_IN_FAILURE',
  EMAIL_SIGN_IN_START: 'EMAIL_SIGN_IN_START',
  EMAIL_SIGN_IN_SUCCESS: 'EMAIL_SIGN_IN_SUCCESS',
  EMAIL_SIGN_IN_FAILURE: 'EMAIL_SIGN_IN_FAILURE',
  CHECK_USER_SESSION: 'CHECK_USER_SESSION'
};

export default UserActionType;